$ANSIBLE_VAULT;1.1;AES256
66633634623864653037303730326332393764636136656434346133663461316634336130363661
6335663735373364663833666638306564643631346433360a656365373034623934313630343035
35623965313234316165666435613731633231613432333865326634616161356438323832616261
3538663166316536610a313730363834396131616532353833373563663836366166376438313732
62326534366335326436333332306562613164356665333130306563303164666532396438643736
37326466383033366536653233353161613130633664633237333230643236356132326432333762
61396139313933616463336237663730326433663639633333343735363835323664333465616565
31613836643835333734343733376666303064323437626661633065653836646331313134633534
36653736636361303033333537663339666238303631656439653063613865336237313833396262
32363966646631303363363732326462646362636330336238336339353466626332623538356633
64366433383562613336383636373338396534646335653136323532656535656563346537313130
39636538373735356162303164313862623532623434393863366462303732623966663437346430
35646234366133333265373666353439616263653866653233623837633133396161323534346237
38633762373263316166663130386636363737356332623963356637343165363065373264326235
66383936336636366162666330616433616664613833623561633866643538366265613465663061
37396234623433633766
